### ISSUE TITLE
hello. When the loss_unsupervised is nearly equal with 0, the loss_supervised is still pretty large, how should I do to get better result?

### ISSUE THREAD

**Issue by fishishappyandfree** [Sleepychord/ImprovedGAN-pytorch#6]
when I run this code, the partial results are as follows.
Iteration 8, loss_supervised = 0.5682, loss_unsupervised = 0.0012, loss_gen = 1.8700 train acc = 0.7541
Eval: correct 6277/ 10000
.......
Iteration 34, loss_supervised = 0.8746, loss_unsupervised = 0.0009, loss_gen = 8.1296 train acc = 0.5644
Eval: correct 8050/ 1800
.......
Iteration 48, loss_supervised = 0.7172, loss_unsupervised = 0.0002, loss_gen = 7.7574 train acc = 0.6869
Eval: correct 8056/ 1800
........
then the results have few change.

**Comment by Sleepychord** [comment]
Have you reduced the batch_size or made other modification? The results are quite different from mine. 

```
Iteration 0, loss_supervised = 0.1650, loss_unsupervised = 0.4635, loss_gen = 0.1599 train acc = 0.9434
Eval: correct 7968 / 10000
```
Can you reproduce the performance using other machines?

**Comment by fishishappyandfree** [comment]
thank you for your help. the above results is gotten after I run this code on other datasets,
