### ISSUE TITLE
Relation with bad GANs

### ISSUE THREAD

**Issue by sakh251** [Sleepychord/ImprovedGAN-pytorch#8]
Hello 
You mentioned this code is inspired from the paper called "Good Semi-supervised Learning
That Requires a Bad GAN". 

Have you changed any part of "Improved Techniques for Training GANs" to close to bad GANs paper?
What are the exact changes?
It is not clear for me. 

Thank you

**Comment by Sleepychord** [comment]
Hi, 
We follow the original designs in "Improved Techniques for Training GANs", except the parts mentioned in the readme.md.
The "bad GAN'' and GraphSGAN papers are just mentioned to explain the principles, because the original paper just takes it as a trick.
