### ISSUE TITLE
change input data

### ISSUE THREAD

**Issue by sakh251** [Sleepychord/ImprovedGAN-pytorch#9]
Hello 
I tried to feed cifar10, I change the input size to 3072, however in run time I still get
(0): LinearWeightNorm(in_features=784, out_features=1000, weight_scale=1)
  (1): LinearWeightNorm(in_features=1000, out_features=500, weight_scale=1)
  (2): LinearWeightNorm(in_features=500, out_features=250, weight_scale=1)
  (3): LinearWeightNorm(in_features=250, out_features=250, weight_scale=1)
  (4): LinearWeightNorm(in_features=250, out_features=250, weight_scale=1)

for first layer it is still 784

**Comment by Sleepychord** [comment]
Hi，maybe the previous models are loaded automatically. I think you can solve it by debugging~

**Comment by sakh251** [comment]
Yes It caused the problem

**Comment by NEUtangyu** [comment]
Hello, I also want to train the model on the cifar dataset now. Is there anything else that the discriminator network needs to change except changing the input to 3*32*32？
